RailMsgSQL:
  Servers:
    Public:
      Bind:
        Address: ":8686"
    Admin:
      Bind:
        Address: ":9696"
  Telemetry:
    ServiceName: "rail-msg-sql"
  Search:
    BackgroundPrepare: true
