RailMsgSQL:
  Servers:
    Public:
      Bind:
        Address: ":8686"
    Admin:
      Bind:
        Address: ":9696"
  Telemetry:
    ServiceName: "rail-msg-sql"
  Search:
    Sqlite:
      Directory: "."
      BusyTimeout: "10s"
      MaxOpenConns: 10
      MaxIdleConns: 5
    BackgroundPrepare: true
